on: pull_request
name: Pull Request
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
        source-url: https://spscommerce.pkgs.visualstudio.com/_packaging/spsc/nuget/v3/index.json
      
    - run: dotnet test MimeKitIssue/MimeKitTests/MimeKitTests.csproj
